@bookRouteURL = http://localhost:8080/book/
@bookID = hehehe
@bookCategory = category
@bookPublishedYear = 2019
@bookAuthor = Savio

### Create Book
POST {{bookRouteURL}} HTTP/1.1
Content-Type: application/json

{
  "title": "Só para garantir",
  "image_url": "https://www.google.com/img.png",
  "author": "Savio",
  "publisher": "Savio Company",
  "isbn": "4523534",
  "price": 119.99,
  "stock": 20,
  "category": "Category One",
  "published_year": 2025,
  "description": "Description to book one"
}

### Get All books
GET {{bookRouteURL}}all

### Get Book by ID
GET {{bookRouteURL}}{{bookID}}

### Get Book by category
GET {{bookRouteURL}}category/{{bookCategory}}

### Get Book by published year
GET {{bookRouteURL}}published-year/{{bookPublishedYear}}

### Get Book by author
GET {{bookRouteURL}}author/{{bookAuthor}}

### Update Book
PUT {{bookRouteURL}}{{bookID}}
Content-Type: application/json

{
  "image_url": "https://www.google.com/img.png",
  "author": "Savio"
}

### Update Book
PATCH {{bookRouteURL}} HTTP/1.1
Content-Type: application/json

{
  "image_url": "https://www.google.com/img.png",
  "author": "Savio"
}


